name: Check Package Licenses
on: pull_request
jobs:
    check:
        name: Check Licenses
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - run: npm ci
            - uses: ./
